"""add project ownership and idempotency

Revision ID: 37226d071f6a
Revises: 510785e5cb68
Create Date: 2026-05-31 23:43:35.237057
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "37226d071f6a"
down_revision: str | None = "510785e5cb68"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "idempotency_records",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=False),
        sa.Column("operation", sa.String(length=100), nullable=False),
        sa.Column("idempotency_key", sa.String(length=300), nullable=False),
        sa.Column("request_hash", sa.String(length=128), nullable=False),
        sa.Column("response_payload", sa.JSON(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "project_id",
            "actor_id",
            "operation",
            "idempotency_key",
            name="uq_idempotency_records_key",
        ),
    )
    op.create_index(
        op.f("ix_idempotency_records_actor_id"), "idempotency_records", ["actor_id"], unique=False
    )
    op.create_index(
        op.f("ix_idempotency_records_project_id"),
        "idempotency_records",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "project_memberships",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "role in ('owner', 'editor', 'viewer')", name="ck_project_memberships_role"
        ),
        sa.CheckConstraint("status in ('active', 'revoked')", name="ck_project_memberships_status"),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "actor_id", name="uq_project_memberships_actor"),
    )
    op.create_index(
        op.f("ix_project_memberships_actor_id"), "project_memberships", ["actor_id"], unique=False
    )
    op.create_index(
        op.f("ix_project_memberships_project_id"),
        "project_memberships",
        ["project_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_project_memberships_project_id"), table_name="project_memberships")
    op.drop_index(op.f("ix_project_memberships_actor_id"), table_name="project_memberships")
    op.drop_table("project_memberships")
    op.drop_index(op.f("ix_idempotency_records_project_id"), table_name="idempotency_records")
    op.drop_index(op.f("ix_idempotency_records_actor_id"), table_name="idempotency_records")
    op.drop_table("idempotency_records")
    # ### end Alembic commands ###
