"""initial production schema

Revision ID: 510785e5cb68
Revises:
Create Date: 2026-05-31 23:11:04.356090
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "510785e5cb68"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def json_type() -> sa.types.TypeEngine:
    if op.get_context().dialect.name == "postgresql":
        return postgresql.JSONB()
    return sa.JSON()


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "agent_review_findings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("draft_candidate_id", sa.Uuid(), nullable=False),
        sa.Column("risk_level", sa.String(length=20), nullable=False),
        sa.Column("risk_type", sa.String(length=80), nullable=False),
        sa.Column("summary", sa.String(length=2000), nullable=False),
        sa.Column("affected_text_ref", sa.String(length=1000), nullable=True),
        sa.Column("memory_refs", json_type(), nullable=False),
        sa.Column("storytelling_refs", json_type(), nullable=False),
        sa.Column("suggested_revision", sa.String(length=4000), nullable=True),
        sa.Column("can_offer_to_author", sa.Boolean(), nullable=False),
        sa.Column("maps_to_review_type_if_accepted", sa.String(length=80), nullable=True),
        sa.Column("draft_local_only", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "maps_to_review_type_if_accepted is null or maps_to_review_type_if_accepted in ('alias_conflict', 'event_merge_conflict', 'state_conflict', 'object_state_conflict', 'knowledge_conflict', 'pov_conflict', 'timeline_conflict', 'relationship_conflict', 'canon_conflict', 'version_conflict', 'source_scope_conflict', 'continuity_warning')",
            name="ck_agent_review_findings_review_mapping",
        ),
        sa.CheckConstraint(
            "risk_level in ('low', 'medium', 'high')", name="ck_agent_review_findings_level"
        ),
        sa.CheckConstraint(
            "risk_type in ('pov_risk', 'knowledge_risk', 'canon_risk', 'unresolved_risk', 'continuity_risk', 'forbidden_knowledge_leak', 'non_pov_mind_reading', 'target_range_risk', 'character_risk', 'agency_break_risk', 'control_risk', 'cast_reuse_risk', 'cast_creation_risk', 'cast_focus_risk', 'cast_complexity_risk', 'cast_policy_violation', 'style_risk', 'exposition_risk', 'dramatization_risk', 'inner_state_overload', 'telling_over_action', 'subtext_missing', 'choice_missing', 'scene_mode_risk', 'sequel_mode_risk', 'mode_mixing_risk', 'no_turn_risk', 'prose_contract_violation', 'inner_state_budget_violation')",
            name="ck_agent_review_findings_type",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_agent_review_findings_draft_candidate_id"),
        "agent_review_findings",
        ["draft_candidate_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_review_findings_project_id"),
        "agent_review_findings",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "audit_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("request_id", sa.String(length=128), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("event_type", sa.String(length=120), nullable=False),
        sa.Column("subject_ref", json_type(), nullable=False),
        sa.Column("decision", json_type(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_audit_events_project_id"), "audit_events", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_request_id"), "audit_events", ["request_id"], unique=False
    )
    op.create_table(
        "job_records",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("job_type", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("idempotency_key", sa.String(length=300), nullable=False),
        sa.Column("payload", json_type(), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("run_after", sa.DateTime(timezone=True), nullable=True),
        sa.Column("locked_by", sa.String(length=100), nullable=True),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.String(length=2000), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status in ('queued', 'running', 'succeeded', 'failed_retryable', 'failed_terminal', 'cancelled')",
            name="ck_job_records_status",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "project_id", "job_type", "idempotency_key", name="uq_job_records_idempotency"
        ),
    )
    op.create_index(op.f("ix_job_records_project_id"), "job_records", ["project_id"], unique=False)
    op.create_table(
        "memory_graph_projection_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("projection_scope", sa.String(length=100), nullable=False),
        sa.Column("source_state_hash", sa.String(length=128), nullable=False),
        sa.Column("created_edge_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_memory_graph_projection_runs_project_id"),
        "memory_graph_projection_runs",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "memory_pages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("page_type", sa.String(length=80), nullable=False),
        sa.Column("target_ref", json_type(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("current_canon", json_type(), nullable=False),
        sa.Column("appearance_log", json_type(), nullable=False),
        sa.Column("event_log", json_type(), nullable=False),
        sa.Column("relationships", json_type(), nullable=False),
        sa.Column("open_threads", json_type(), nullable=False),
        sa.Column("contradictions", json_type(), nullable=False),
        sa.Column("source_refs", json_type(), nullable=False),
        sa.Column("canon_status", sa.String(length=80), nullable=False),
        sa.Column("memory_depth", sa.String(length=80), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_memory_pages_project_id"), "memory_pages", ["project_id"], unique=False
    )
    op.create_table(
        "review_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("review_type", sa.String(length=80), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("summary", sa.String(length=2000), nullable=False),
        sa.Column("affected_refs", json_type(), nullable=False),
        sa.Column("new_evidence", json_type(), nullable=False),
        sa.Column("existing_evidence", json_type(), nullable=False),
        sa.Column("suggested_actions", json_type(), nullable=False),
        sa.Column("default_action", sa.String(length=100), nullable=False),
        sa.Column("resolution", sa.String(length=100), nullable=True),
        sa.Column("resolved_by", sa.Uuid(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("side_effects", json_type(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "resolution is null or resolution in ('accept', 'reject', 'split', 'merge', 'mark_intentional', 'supersede', 'needs_memory_update', 'fixed_by_text_edit', 'accepted_as_change')",
            name="ck_review_items_resolution",
        ),
        sa.CheckConstraint(
            "review_type in ('alias_conflict', 'event_merge_conflict', 'state_conflict', 'object_state_conflict', 'knowledge_conflict', 'pov_conflict', 'timeline_conflict', 'relationship_conflict', 'canon_conflict', 'version_conflict', 'source_scope_conflict', 'continuity_warning')",
            name="ck_review_items_review_type",
        ),
        sa.CheckConstraint(
            "severity in ('low', 'medium', 'high')", name="ck_review_items_severity"
        ),
        sa.CheckConstraint(
            "status in ('open', 'dismissed', 'resolved', 'superseded')",
            name="ck_review_items_status",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_review_items_project_id"), "review_items", ["project_id"], unique=False
    )
    op.create_table(
        "skill_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("skill_name", sa.String(length=120), nullable=False),
        sa.Column("skill_version", sa.String(length=80), nullable=False),
        sa.Column("input_schema_version", sa.String(length=80), nullable=False),
        sa.Column("output_schema_version", sa.String(length=80), nullable=False),
        sa.Column("prompt_version", sa.String(length=80), nullable=False),
        sa.Column("input_hash", sa.String(length=128), nullable=False),
        sa.Column("structured_output", json_type(), nullable=False),
        sa.Column("validation_result", json_type(), nullable=False),
        sa.Column("raw_output_ref", sa.String(length=1000), nullable=True),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("cost_cents", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status in ('started', 'succeeded', 'failed_retryable', 'failed_terminal')",
            name="ck_skill_runs_status",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_skill_runs_project_id"), "skill_runs", ["project_id"], unique=False)
    op.create_table(
        "source_raw_sources",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("source_type", sa.String(length=40), nullable=False),
        sa.Column("source_scope", sa.String(length=40), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("ownership_status", sa.String(length=40), nullable=False),
        sa.Column("raw_text_ref", sa.String(length=1000), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "ownership_status in ('owned', 'authorized', 'user_provided', 'unknown')",
            name="ck_source_raw_sources_ownership_status",
        ),
        sa.CheckConstraint(
            "source_scope in ('user_draft', 'user_published', 'external_canon', 'author_note', 'outline_plan', 'reference_only', 'discarded_draft', 'experimental', 'model_suggestion')",
            name="ck_source_raw_sources_source_scope",
        ),
        sa.CheckConstraint(
            "source_type in ('draft_manuscript', 'canon_source', 'web_serial', 'pdf_book', 'ocr_text', 'author_notes', 'outline', 'character_sheet', 'worldbuilding', 'model_output', 'other')",
            name="ck_source_raw_sources_source_type",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_source_raw_sources_project_id"), "source_raw_sources", ["project_id"], unique=False
    )
    op.create_table(
        "story_alias_records",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("alias_text", sa.String(length=500), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=True),
        sa.Column("alias_type", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(length=80), nullable=False),
        sa.Column("scope", sa.String(length=80), nullable=False),
        sa.Column("evidence_span_ids", json_type(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status in ('auto_accepted', 'proposed', 'rejected', 'user_confirmed', 'user_corrected')",
            name="ck_story_alias_records_status",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_story_alias_records_entity_id"), "story_alias_records", ["entity_id"], unique=False
    )
    op.create_index(
        op.f("ix_story_alias_records_project_id"),
        "story_alias_records",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "story_fact_assertions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("subject_ref", json_type(), nullable=False),
        sa.Column("predicate", sa.String(length=120), nullable=False),
        sa.Column("object_ref", json_type(), nullable=False),
        sa.Column("fact_status", sa.String(length=40), nullable=False),
        sa.Column("valid_from_scene_id", sa.Uuid(), nullable=True),
        sa.Column("valid_until_scene_id", sa.Uuid(), nullable=True),
        sa.Column("evidence_span_ids", json_type(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("source_scope", sa.String(length=40), nullable=False),
        sa.Column("promotion_decision_id", sa.Uuid(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "fact_status != 'canon' or promotion_decision_id is not null",
            name="ck_story_fact_assertions_canon_requires_promotion",
        ),
        sa.CheckConstraint(
            "fact_status in ('proposed', 'inferred', 'canon', 'disputed', 'contradicted', 'outdated', 'user_note')",
            name="ck_story_fact_assertions_status",
        ),
        sa.CheckConstraint(
            "not (source_scope = 'model_suggestion' and fact_status = 'canon')",
            name="ck_story_fact_assertions_model_suggestion_not_canon",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_story_fact_assertions_project_id"),
        "story_fact_assertions",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "memory_graph_projection_edges",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("source_ref", json_type(), nullable=False),
        sa.Column("subject_ref", json_type(), nullable=False),
        sa.Column("relation", sa.String(length=100), nullable=False),
        sa.Column("target_ref", json_type(), nullable=False),
        sa.Column("edge_status", sa.String(length=40), nullable=False),
        sa.Column("evidence_refs", json_type(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "edge_status in ('canon', 'proposed', 'inferred', 'disputed', 'contradicted', 'outdated', 'discarded')",
            name="ck_memory_graph_projection_edges_status",
        ),
        sa.CheckConstraint(
            "relation in ('appears_in', 'present_at', 'occurred_at', 'involves_object', 'located_in', 'owns', 'member_of', 'family_of', 'ally_of', 'enemy_of', 'knows', 'does_not_know', 'reveals', 'causes', 'follows', 'foreshadows', 'contradicts', 'belongs_to_plotline', 'related_to')",
            name="ck_memory_graph_projection_edges_relation",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["memory_graph_projection_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "project_id",
            "source_ref",
            "relation",
            "target_ref",
            name="uq_memory_graph_projection_edges_identity",
        ),
    )
    op.create_index(
        op.f("ix_memory_graph_projection_edges_project_id"),
        "memory_graph_projection_edges",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "source_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("version_label", sa.String(length=100), nullable=False),
        sa.Column("raw_hash", sa.String(length=128), nullable=False),
        sa.Column("supersedes_version_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source_raw_sources.id"],
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_version_id"],
            ["source_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id", "raw_hash", name="uq_source_versions_hash"),
    )
    op.create_index(
        op.f("ix_source_versions_source_id"), "source_versions", ["source_id"], unique=False
    )
    op.create_table(
        "source_accepted_fragments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("candidate_id", sa.Uuid(), nullable=False),
        sa.Column("target_source_id", sa.Uuid(), nullable=False),
        sa.Column("target_version_id", sa.Uuid(), nullable=False),
        sa.Column("accepted_text_ref", sa.String(length=1000), nullable=False),
        sa.Column("range_start", sa.Integer(), nullable=False),
        sa.Column("range_end", sa.Integer(), nullable=False),
        sa.Column("source_type", sa.String(length=40), nullable=False),
        sa.Column("source_scope", sa.String(length=40), nullable=False),
        sa.Column("author_edited", sa.Boolean(), nullable=False),
        sa.Column("accepted_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("range_end >= range_start", name="ck_source_accepted_fragments_range"),
        sa.CheckConstraint("range_start >= 0", name="ck_source_accepted_fragments_start"),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_source_id"],
            ["source_raw_sources.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_version_id"],
            ["source_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_source_accepted_fragments_candidate_id"),
        "source_accepted_fragments",
        ["candidate_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_source_accepted_fragments_project_id"),
        "source_accepted_fragments",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_source_accepted_fragments_target_source_id"),
        "source_accepted_fragments",
        ["target_source_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_source_accepted_fragments_target_version_id"),
        "source_accepted_fragments",
        ["target_version_id"],
        unique=False,
    )
    op.create_table(
        "source_processed_views",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("version_id", sa.Uuid(), nullable=False),
        sa.Column("cleaning_profile", sa.String(length=100), nullable=False),
        sa.Column("markdown_ref", sa.String(length=1000), nullable=False),
        sa.Column("raw_offset_map_ref", sa.String(length=1000), nullable=False),
        sa.Column("view_status", sa.String(length=40), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "view_status in ('current', 'stale', 'rebuilt', 'deprecated')",
            name="ck_source_processed_views_status",
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["source_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_source_processed_views_version_id"),
        "source_processed_views",
        ["version_id"],
        unique=False,
    )
    op.create_index(
        "uq_source_processed_views_current_version",
        "source_processed_views",
        ["version_id"],
        unique=True,
        sqlite_where=sa.text("view_status = 'current'"),
        postgresql_where=sa.text("view_status = 'current'"),
    )
    op.create_table(
        "source_deltas",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("previous_version_id", sa.Uuid(), nullable=True),
        sa.Column("accepted_fragment_id", sa.Uuid(), nullable=True),
        sa.Column("delta_kind", sa.String(length=20), nullable=False),
        sa.Column("range_start", sa.Integer(), nullable=False),
        sa.Column("range_end", sa.Integer(), nullable=False),
        sa.Column("base_hash", sa.String(length=128), nullable=True),
        sa.Column("submitted_text_ref", sa.String(length=1000), nullable=False),
        sa.Column("source_type", sa.String(length=40), nullable=False),
        sa.Column("source_scope", sa.String(length=40), nullable=False),
        sa.Column("provenance", json_type(), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "delta_kind in ('insert', 'replace', 'delete')", name="ck_source_deltas_kind"
        ),
        sa.CheckConstraint(
            "status in ('submitted', 'source_version_created', 'normalized', 'span_extracted', 'memory_writeback_queued', 'memory_writeback_completed', 'rejected_stale_base')",
            name="ck_source_deltas_status",
        ),
        sa.CheckConstraint("range_end >= range_start", name="ck_source_deltas_range"),
        sa.CheckConstraint("range_start >= 0", name="ck_source_deltas_start"),
        sa.ForeignKeyConstraint(
            ["accepted_fragment_id"],
            ["source_accepted_fragments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["previous_version_id"],
            ["source_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source_raw_sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_source_deltas_accepted_fragment_id"),
        "source_deltas",
        ["accepted_fragment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_source_deltas_previous_version_id"),
        "source_deltas",
        ["previous_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_source_deltas_project_id"), "source_deltas", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_source_deltas_source_id"), "source_deltas", ["source_id"], unique=False
    )
    op.create_table(
        "source_spans",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("version_id", sa.Uuid(), nullable=False),
        sa.Column("view_id", sa.Uuid(), nullable=False),
        sa.Column("chapter_id", sa.Uuid(), nullable=True),
        sa.Column("scene_id", sa.Uuid(), nullable=True),
        sa.Column("start_offset", sa.Integer(), nullable=False),
        sa.Column("end_offset", sa.Integer(), nullable=False),
        sa.Column("raw_start_offset", sa.Integer(), nullable=False),
        sa.Column("raw_end_offset", sa.Integer(), nullable=False),
        sa.Column("text_preview", sa.String(length=500), nullable=False),
        sa.Column("speaker_entity_id", sa.Uuid(), nullable=True),
        sa.Column("narration_layer", sa.String(length=40), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "narration_layer in ('narrator', 'dialogue', 'inner_thought', 'author_note')",
            name="ck_source_spans_narration_layer",
        ),
        sa.CheckConstraint("end_offset > start_offset", name="ck_source_spans_range"),
        sa.CheckConstraint("raw_end_offset > raw_start_offset", name="ck_source_spans_raw_range"),
        sa.CheckConstraint("raw_start_offset >= 0", name="ck_source_spans_raw_start_non_negative"),
        sa.CheckConstraint("start_offset >= 0", name="ck_source_spans_start_non_negative"),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source_raw_sources.id"],
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["source_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["view_id"],
            ["source_processed_views.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_source_spans_source_id"), "source_spans", ["source_id"], unique=False)
    op.create_index(
        op.f("ix_source_spans_version_id"), "source_spans", ["version_id"], unique=False
    )
    op.create_index(op.f("ix_source_spans_view_id"), "source_spans", ["view_id"], unique=False)
    op.create_table(
        "story_chapters",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("view_id", sa.Uuid(), nullable=False),
        sa.Column("chapter_index", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("start_offset", sa.Integer(), nullable=False),
        sa.Column("end_offset", sa.Integer(), nullable=False),
        sa.Column("summary", sa.String(length=2000), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("chapter_index >= 0", name="ck_story_chapters_index"),
        sa.CheckConstraint("end_offset > start_offset", name="ck_story_chapters_range"),
        sa.ForeignKeyConstraint(
            ["view_id"],
            ["source_processed_views.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("view_id", "chapter_index", name="uq_story_chapters_view_index"),
    )
    op.create_index(op.f("ix_story_chapters_view_id"), "story_chapters", ["view_id"], unique=False)
    op.create_table(
        "memory_character_knowledge",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("character_id", sa.Uuid(), nullable=False),
        sa.Column("knows_ref", json_type(), nullable=False),
        sa.Column("learned_in_scene_id", sa.Uuid(), nullable=True),
        sa.Column("evidence_span_id", sa.Uuid(), nullable=False),
        sa.Column("certainty", sa.String(length=80), nullable=False),
        sa.Column("hidden_from", json_type(), nullable=False),
        sa.Column("status", sa.String(length=80), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["evidence_span_id"],
            ["source_spans.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_memory_character_knowledge_character_id"),
        "memory_character_knowledge",
        ["character_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_memory_character_knowledge_project_id"),
        "memory_character_knowledge",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "story_mentions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("span_id", sa.Uuid(), nullable=False),
        sa.Column("raw_text", sa.String(length=500), nullable=False),
        sa.Column("mention_type", sa.String(length=80), nullable=False),
        sa.Column("local_context", sa.String(length=2000), nullable=True),
        sa.Column("resolved_entity_id", sa.Uuid(), nullable=True),
        sa.Column("resolution_status", sa.String(length=80), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["span_id"],
            ["source_spans.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_story_mentions_span_id"), "story_mentions", ["span_id"], unique=False)
    op.create_table(
        "story_scenes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("chapter_id", sa.Uuid(), nullable=False),
        sa.Column("scene_index", sa.Integer(), nullable=False),
        sa.Column("location_entity_id", sa.Uuid(), nullable=True),
        sa.Column("pov_character_id", sa.Uuid(), nullable=True),
        sa.Column("pov_mode", sa.String(length=100), nullable=True),
        sa.Column("story_time", sa.String(length=200), nullable=True),
        sa.Column("emotional_tone", sa.String(length=200), nullable=True),
        sa.Column("scene_summary", sa.String(length=2000), nullable=True),
        sa.Column("scene_function", sa.String(length=200), nullable=True),
        sa.Column("start_offset", sa.Integer(), nullable=False),
        sa.Column("end_offset", sa.Integer(), nullable=False),
        sa.CheckConstraint("end_offset > start_offset", name="ck_story_scenes_range"),
        sa.CheckConstraint("scene_index >= 0", name="ck_story_scenes_index"),
        sa.ForeignKeyConstraint(
            ["chapter_id"],
            ["story_chapters.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("chapter_id", "scene_index", name="uq_story_scenes_chapter_index"),
    )
    op.create_index(
        op.f("ix_story_scenes_chapter_id"), "story_scenes", ["chapter_id"], unique=False
    )
    op.create_table(
        "agent_action_requests",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column("source_version_id", sa.Uuid(), nullable=True),
        sa.Column("scene_id", sa.Uuid(), nullable=True),
        sa.Column("chapter_id", sa.Uuid(), nullable=True),
        sa.Column("pov_character_id", sa.Uuid(), nullable=True),
        sa.Column("actor_intent", sa.String(length=4000), nullable=False),
        sa.Column("trigger", sa.String(length=80), nullable=False),
        sa.Column("action_type", sa.String(length=100), nullable=False),
        sa.Column("target", json_type(), nullable=True),
        sa.Column("constraints", json_type(), nullable=False),
        sa.Column("expected_output", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status in ('submitted', 'running', 'succeeded', 'failed', 'cancelled')",
            name="ck_agent_action_requests_status",
        ),
        sa.ForeignKeyConstraint(
            ["chapter_id"],
            ["story_chapters.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["scene_id"],
            ["story_scenes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source_raw_sources.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_version_id"],
            ["source_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_agent_action_requests_project_id"),
        "agent_action_requests",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "story_canonical_entities",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("entity_type", sa.String(length=80), nullable=False),
        sa.Column("display_name", sa.String(length=500), nullable=False),
        sa.Column("canonical_status", sa.String(length=80), nullable=False),
        sa.Column("cast_tier", sa.String(length=80), nullable=True),
        sa.Column("first_seen_scene_id", sa.Uuid(), nullable=True),
        sa.Column("description", sa.String(length=4000), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["first_seen_scene_id"],
            ["story_scenes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_story_canonical_entities_project_id"),
        "story_canonical_entities",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "story_canonical_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=80), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("event_status", sa.String(length=80), nullable=False),
        sa.Column("primary_scene_id", sa.Uuid(), nullable=True),
        sa.Column("event_candidate_ids", json_type(), nullable=False),
        sa.Column("participants", json_type(), nullable=False),
        sa.Column("objects", json_type(), nullable=False),
        sa.Column("location_entity_id", sa.Uuid(), nullable=True),
        sa.Column("story_time", sa.String(length=200), nullable=True),
        sa.Column("summary", sa.String(length=2000), nullable=False),
        sa.Column("consequence_summary", sa.String(length=2000), nullable=True),
        sa.Column("evidence_span_ids", json_type(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["primary_scene_id"],
            ["story_scenes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_story_canonical_events_project_id"),
        "story_canonical_events",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "story_event_candidates",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("scene_id", sa.Uuid(), nullable=True),
        sa.Column("event_type", sa.String(length=80), nullable=False),
        sa.Column("summary", sa.String(length=2000), nullable=False),
        sa.Column("participants", json_type(), nullable=False),
        sa.Column("objects", json_type(), nullable=False),
        sa.Column("location_entity_id", sa.Uuid(), nullable=True),
        sa.Column("state_change", json_type(), nullable=False),
        sa.Column("evidence_span_ids", json_type(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("aggregation_status", sa.String(length=80), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["scene_id"],
            ["story_scenes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_story_event_candidates_project_id"),
        "story_event_candidates",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_story_event_candidates_scene_id"),
        "story_event_candidates",
        ["scene_id"],
        unique=False,
    )
    op.create_table(
        "agent_draft_candidates",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("action_request_id", sa.Uuid(), nullable=False),
        sa.Column("mode", sa.String(length=100), nullable=False),
        sa.Column("candidate_text_ref", sa.String(length=1000), nullable=False),
        sa.Column("context_pack_id", sa.Uuid(), nullable=True),
        sa.Column("selected_beat_id", sa.Uuid(), nullable=True),
        sa.Column("target_source_id", sa.Uuid(), nullable=True),
        sa.Column("target_version_id", sa.Uuid(), nullable=True),
        sa.Column("target_scene_id", sa.Uuid(), nullable=True),
        sa.Column("affected_range", json_type(), nullable=True),
        sa.Column("base_hash", sa.String(length=128), nullable=True),
        sa.Column("memory_refs", json_type(), nullable=False),
        sa.Column("evidence_refs", json_type(), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("author_action", sa.String(length=80), nullable=True),
        sa.Column("accepted_text_ref", sa.String(length=1000), nullable=True),
        sa.Column("override_reason", sa.String(length=1000), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status in ('generated', 'reviewed', 'offered_to_author', 'accepted', 'revised', 'rejected', 'blocked', 'archived', 'converted_to_source_delta')",
            name="ck_agent_draft_candidates_status",
        ),
        sa.ForeignKeyConstraint(
            ["action_request_id"],
            ["agent_action_requests.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_scene_id"],
            ["story_scenes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_source_id"],
            ["source_raw_sources.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_version_id"],
            ["source_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_agent_draft_candidates_action_request_id"),
        "agent_draft_candidates",
        ["action_request_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_draft_candidates_project_id"),
        "agent_draft_candidates",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "memory_evidence_log_entries",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("log_type", sa.String(length=100), nullable=False),
        sa.Column("target_ref", json_type(), nullable=False),
        sa.Column("fact_id", sa.Uuid(), nullable=True),
        sa.Column("event_id", sa.Uuid(), nullable=True),
        sa.Column("source_span_ids", json_type(), nullable=False),
        sa.Column("log_status", sa.String(length=80), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source_span_ids is not null", name="ck_memory_evidence_log_entries_source_spans"
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["story_canonical_events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["fact_id"],
            ["story_fact_assertions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_memory_evidence_log_entries_project_id"),
        "memory_evidence_log_entries",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "agent_storytelling_controls",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("action_request_id", sa.Uuid(), nullable=True),
        sa.Column("draft_candidate_id", sa.Uuid(), nullable=True),
        sa.Column("control_type", sa.String(length=80), nullable=False),
        sa.Column("schema_version", sa.String(length=40), nullable=False),
        sa.Column("payload", json_type(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "control_type in ('role_slot', 'character_casting_decision', 'new_character_seed', 'scene_sequel_mode', 'dramatic_behavior_plan', 'prose_rendering_contract')",
            name="ck_agent_storytelling_controls_type",
        ),
        sa.ForeignKeyConstraint(
            ["action_request_id"],
            ["agent_action_requests.id"],
        ),
        sa.ForeignKeyConstraint(
            ["draft_candidate_id"],
            ["agent_draft_candidates.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_agent_storytelling_controls_project_id"),
        "agent_storytelling_controls",
        ["project_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_agent_storytelling_controls_project_id"), table_name="agent_storytelling_controls"
    )
    op.drop_table("agent_storytelling_controls")
    op.drop_index(
        op.f("ix_memory_evidence_log_entries_project_id"), table_name="memory_evidence_log_entries"
    )
    op.drop_table("memory_evidence_log_entries")
    op.drop_index(op.f("ix_agent_draft_candidates_project_id"), table_name="agent_draft_candidates")
    op.drop_index(
        op.f("ix_agent_draft_candidates_action_request_id"), table_name="agent_draft_candidates"
    )
    op.drop_table("agent_draft_candidates")
    op.drop_index(op.f("ix_story_event_candidates_scene_id"), table_name="story_event_candidates")
    op.drop_index(op.f("ix_story_event_candidates_project_id"), table_name="story_event_candidates")
    op.drop_table("story_event_candidates")
    op.drop_index(op.f("ix_story_canonical_events_project_id"), table_name="story_canonical_events")
    op.drop_table("story_canonical_events")
    op.drop_index(
        op.f("ix_story_canonical_entities_project_id"), table_name="story_canonical_entities"
    )
    op.drop_table("story_canonical_entities")
    op.drop_index(op.f("ix_agent_action_requests_project_id"), table_name="agent_action_requests")
    op.drop_table("agent_action_requests")
    op.drop_index(op.f("ix_story_scenes_chapter_id"), table_name="story_scenes")
    op.drop_table("story_scenes")
    op.drop_index(op.f("ix_story_mentions_span_id"), table_name="story_mentions")
    op.drop_table("story_mentions")
    op.drop_index(
        op.f("ix_memory_character_knowledge_project_id"), table_name="memory_character_knowledge"
    )
    op.drop_index(
        op.f("ix_memory_character_knowledge_character_id"), table_name="memory_character_knowledge"
    )
    op.drop_table("memory_character_knowledge")
    op.drop_index(op.f("ix_story_chapters_view_id"), table_name="story_chapters")
    op.drop_table("story_chapters")
    op.drop_index(op.f("ix_source_spans_view_id"), table_name="source_spans")
    op.drop_index(op.f("ix_source_spans_version_id"), table_name="source_spans")
    op.drop_index(op.f("ix_source_spans_source_id"), table_name="source_spans")
    op.drop_table("source_spans")
    op.drop_index(op.f("ix_source_deltas_source_id"), table_name="source_deltas")
    op.drop_index(op.f("ix_source_deltas_project_id"), table_name="source_deltas")
    op.drop_index(op.f("ix_source_deltas_previous_version_id"), table_name="source_deltas")
    op.drop_index(op.f("ix_source_deltas_accepted_fragment_id"), table_name="source_deltas")
    op.drop_table("source_deltas")
    op.drop_index(
        "uq_source_processed_views_current_version",
        table_name="source_processed_views",
        sqlite_where=sa.text("view_status = 'current'"),
        postgresql_where=sa.text("view_status = 'current'"),
    )
    op.drop_index(op.f("ix_source_processed_views_version_id"), table_name="source_processed_views")
    op.drop_table("source_processed_views")
    op.drop_index(
        op.f("ix_source_accepted_fragments_target_version_id"),
        table_name="source_accepted_fragments",
    )
    op.drop_index(
        op.f("ix_source_accepted_fragments_target_source_id"),
        table_name="source_accepted_fragments",
    )
    op.drop_index(
        op.f("ix_source_accepted_fragments_project_id"), table_name="source_accepted_fragments"
    )
    op.drop_index(
        op.f("ix_source_accepted_fragments_candidate_id"), table_name="source_accepted_fragments"
    )
    op.drop_table("source_accepted_fragments")
    op.drop_index(op.f("ix_source_versions_source_id"), table_name="source_versions")
    op.drop_table("source_versions")
    op.drop_index(
        op.f("ix_memory_graph_projection_edges_project_id"),
        table_name="memory_graph_projection_edges",
    )
    op.drop_table("memory_graph_projection_edges")
    op.drop_index(op.f("ix_story_fact_assertions_project_id"), table_name="story_fact_assertions")
    op.drop_table("story_fact_assertions")
    op.drop_index(op.f("ix_story_alias_records_project_id"), table_name="story_alias_records")
    op.drop_index(op.f("ix_story_alias_records_entity_id"), table_name="story_alias_records")
    op.drop_table("story_alias_records")
    op.drop_index(op.f("ix_source_raw_sources_project_id"), table_name="source_raw_sources")
    op.drop_table("source_raw_sources")
    op.drop_index(op.f("ix_skill_runs_project_id"), table_name="skill_runs")
    op.drop_table("skill_runs")
    op.drop_index(op.f("ix_review_items_project_id"), table_name="review_items")
    op.drop_table("review_items")
    op.drop_index(op.f("ix_memory_pages_project_id"), table_name="memory_pages")
    op.drop_table("memory_pages")
    op.drop_index(
        op.f("ix_memory_graph_projection_runs_project_id"),
        table_name="memory_graph_projection_runs",
    )
    op.drop_table("memory_graph_projection_runs")
    op.drop_index(op.f("ix_job_records_project_id"), table_name="job_records")
    op.drop_table("job_records")
    op.drop_index(op.f("ix_audit_events_request_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_project_id"), table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index(op.f("ix_agent_review_findings_project_id"), table_name="agent_review_findings")
    op.drop_index(
        op.f("ix_agent_review_findings_draft_candidate_id"), table_name="agent_review_findings"
    )
    op.drop_table("agent_review_findings")
    op.drop_table("projects")
    # ### end Alembic commands ###
