"""add writing context packs

Revision ID: 5a73073bd5ac
Revises: 37226d071f6a
Create Date: 2026-05-31 23:54:40.097850
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "5a73073bd5ac"
down_revision: str | None = "37226d071f6a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_context_packs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("action_request_id", sa.Uuid(), nullable=True),
        sa.Column("current_source_id", sa.Uuid(), nullable=True),
        sa.Column("current_version_id", sa.Uuid(), nullable=True),
        sa.Column("current_scene_id", sa.Uuid(), nullable=True),
        sa.Column("current_pov_character_id", sa.Uuid(), nullable=True),
        sa.Column("mode", sa.String(length=100), nullable=False),
        sa.Column("schema_version", sa.String(length=40), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("evidence_refs", sa.JSON(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["action_request_id"],
            ["agent_action_requests.id"],
        ),
        sa.ForeignKeyConstraint(
            ["current_scene_id"],
            ["story_scenes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["current_source_id"],
            ["source_raw_sources.id"],
        ),
        sa.ForeignKeyConstraint(
            ["current_version_id"],
            ["source_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_agent_context_packs_action_request_id"),
        "agent_context_packs",
        ["action_request_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_context_packs_project_id"),
        "agent_context_packs",
        ["project_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_agent_context_packs_project_id"), table_name="agent_context_packs")
    op.drop_index(
        op.f("ix_agent_context_packs_action_request_id"), table_name="agent_context_packs"
    )
    op.drop_table("agent_context_packs")
    # ### end Alembic commands ###
